### ISSUE TITLE
Realizare metoda care returneaza statistici

### ISSUE THREAD

**Issue by Exhum3d** [Vlad-imeer/app-arbore-binar#3]
Aici este vorba de o metoda care sa actualizeze urmatoarele proprietati:
- Nr. noduri
- Nr. frunze
- Nr. niveluri

**Comment by v36u** [comment]
Acest issue va fi rezolvat după sau în timpul implementării lui #7.

**Comment by v36u** [comment]
Rezolvat în #7.
